<a href="https://colab.research.google.com/github/4sTr0J/NLP_Group_02/blob/features%2FCIT-24-01-0249-Random-Forest%2BCNN/NLP_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

print(os.path.exists("/content/drive/MyDrive/Data Set/vulnerabilities.csv"))

True

In [5]:
import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.csv'):
            print(os.path.join(root, file))

/content/drive/MyDrive/First Semester/Mathematics for Computing/country_vaccinations_by_manufacturer.csv
/content/drive/MyDrive/First Semester/Mathematics for Computing/ClimateChangeData.csv
/content/drive/MyDrive/Data Set/vulnerabilities.csv
/content/drive/MyDrive/Data Set/vulnerabilities_50000.csv

In [6]:
dataset_path = "/content/drive/MyDrive/Data Set/vulnerabilities.csv"

In [8]:
#Load Dataset
import pandas as pd
df = pd.read_csv(dataset_path)
display(df)

,func,target,cwe,project,commit_id,hash,size,message
0,int _gnutls_ciphertext2compressed(gnutls_sessi...,1,NaN,gnutls,7ad6162573ba79a4392c63b453ad0220ca6c5ace,73008646937836648589283922871188272089,157,added an extra check while checking the padding.
1,static char *make_filename_safe(const char *fi...,1,CWE-264,php-src,055ecbc62878e86287d742c7246c21606cee8183,211824207069112513181516095447837228041,22,Improve check for :memory: pseudo-filename in ...
2,"unpack_Z_stream(int fd_in, int fd_out)\n{\n\tI...",1,NaN,busybox,251fc70e9722f931eec23a34030d05ba5f747b0e,21401706257394042943815500829552774160,232,uncompress: fix buffer underrun by corrupted i...
3,"static void cirrus_do_copy(CirrusVGAState *s, ...",1,CWE-787,qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,135590882627853658533498335902319684573,66,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."
4,"glue(cirrus_bitblt_rop_fwd_, ROP_NAME)(CirrusV...",1,CWE-787,qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,27696392987383562433164405181263025184,18,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."
...,...,...,...,...,...,...,...,...
320777,inline void StreamResource::EmitRead(ssize_t n...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,191666183590885386921438642282124547733,8,src: use unique_ptr for WriteWrap\n\nThis comm...
320778,void StreamBase::JSMethod(const FunctionCallba...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,257679158413882759024687732393060082473,11,src: use unique_ptr for WriteWrap\n\nThis comm...
320779,~CloseReq() {\n uv_fs_req_cleanup(req...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,95849745532474044086293722840152017667,5,src: use unique_ptr for WriteWrap\n\nThis comm...
320780,void PackSettings(const FunctionCallbackInfo<V...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,308185826333582152350706380559538897481,12,src: use unique_ptr for WriteWrap\n\nThis comm...
320781,"void Initialize(Local<Object> target,\n ...",0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,13835898906479445212427382528307645781,221,src: use unique_ptr for WriteWrap\n\nThis comm...

In [ ]:
#Check Dataset Information
df.info()
print("***************************************")
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320782 entries, 0 to 320781
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   func       320781 non-null  object
 1   target     320782 non-null  int64
 2   cwe        273707 non-null  object
 3   project    320782 non-null  object
 4   commit_id  320782 non-null  object
 5   hash       320782 non-null  object
 6   size       320782 non-null  int64
 7   message    320596 non-null  object
dtypes: int64(2), object(6)
memory usage: 19.6+ MB
***************************************

              target           size
count  320782.000000  320782.000000
mean        0.059059      43.932605
std         0.235735     126.734921
min         0.000000       1.000000
25%         0.000000       9.000000
50%         0.000000      19.000000
75%         0.000000      43.000000
max         1.000000   24047.000000

In [ ]:
#Check Missing Values
df.isnull().sum()

df.dropna(subset=["cwe"], inplace=True)

In [ ]:
#Remove Duplicate Records
df.duplicated().sum()
df.drop_duplicates(inplace=True)
#print(df)

In [ ]:
#Remove Unnecessary Spaces
text_columns = ['func','cwe','project','message']

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

display(df.head())

,func,target,cwe,project,commit_id,hash,size,message
0,int _gnutls_ciphertext2compressed(gnutls_sessi...,1,nan,gnutls,7ad6162573ba79a4392c63b453ad0220ca6c5ace,73008646937836648589283922871188272089,157,added an extra check while checking the padding.
1,static char *make_filename_safe(const char *fi...,1,CWE-264,php-src,055ecbc62878e86287d742c7246c21606cee8183,211824207069112513181516095447837228041,22,Improve check for :memory: pseudo-filename in ...
2,"unpack_Z_stream(int fd_in, int fd_out)\n{\n\tI...",1,nan,busybox,251fc70e9722f931eec23a34030d05ba5f747b0e,21401706257394042943815500829552774160,232,uncompress: fix buffer underrun by corrupted i...
3,"static void cirrus_do_copy(CirrusVGAState *s, ...",1,CWE-787,qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,135590882627853658533498335902319684573,66,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."
4,"glue(cirrus_bitblt_rop_fwd_, ROP_NAME)(CirrusV...",1,CWE-787,qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,27696392987383562433164405181263025184,18,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."

In [ ]:
#Convert Data Types
df['target'] = df['target'].astype(int)
display(df)

,func,target,cwe,project,commit_id,hash,size,message
0,int _gnutls_ciphertext2compressed(gnutls_sessi...,1,Unknown,gnutls,7ad6162573ba79a4392c63b453ad0220ca6c5ace,73008646937836648589283922871188272089,157,added an extra check while checking the padding.
1,static char *make_filename_safe(const char *fi...,1,CWE-264,php-src,055ecbc62878e86287d742c7246c21606cee8183,211824207069112513181516095447837228041,22,Improve check for :memory: pseudo-filename in ...
2,"unpack_Z_stream(int fd_in, int fd_out)\n{\n\tI...",1,Unknown,busybox,251fc70e9722f931eec23a34030d05ba5f747b0e,21401706257394042943815500829552774160,232,uncompress: fix buffer underrun by corrupted i...
3,"static void cirrus_do_copy(CirrusVGAState *s, ...",1,CWE-787,qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,135590882627853658533498335902319684573,66,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."
4,"glue(cirrus_bitblt_rop_fwd_, ROP_NAME)(CirrusV...",1,CWE-787,qemu,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,27696392987383562433164405181263025184,18,"CVE-2007-1320 - Cirrus LGD-54XX ""bitblt"" heap ..."
...,...,...,...,...,...,...,...,...
320777,inline void StreamResource::EmitRead(ssize_t n...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,191666183590885386921438642282124547733,8,src: use unique_ptr for WriteWrap\n\nThis comm...
320778,void StreamBase::JSMethod(const FunctionCallba...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,257679158413882759024687732393060082473,11,src: use unique_ptr for WriteWrap\n\nThis comm...
320779,~CloseReq() {\n uv_fs_req_cleanup(req());...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,95849745532474044086293722840152017667,5,src: use unique_ptr for WriteWrap\n\nThis comm...
320780,void PackSettings(const FunctionCallbackInfo<V...,0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,308185826333582152350706380559538897481,12,src: use unique_ptr for WriteWrap\n\nThis comm...
320781,"void Initialize(Local<Object> target,\n ...",0,CWE-416,node,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,13835898906479445212427382528307645781,221,src: use unique_ptr for WriteWrap\n\nThis comm...

In [47]:
#Check Unique Target Values
df['target'].value_counts()

target
0    301837
1     18945
Name: count, dtype: int64

In [48]:
#Remove Special Characters from Text Columns
import re

def clean_text(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', str(text))
    text = re.sub(r'\s+', ' ', text)
    return text.lower()

for col in ['func','cwe','project','message']:
    df[col] = df[col].apply(clean_text)

In [52]:
#Encode Categorical Features
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['project'] = le.fit_transform(df['project'])
df['cwe'] = le.fit_transform(df['cwe'])
df['func'] = le.fit_transform(df['func'])

display(df)

,func,target,cwe,project,commit_id,hash,size,message
0,73113,1,625,215,7ad6162573ba79a4392c63b453ad0220ca6c5ace,73008646937836648589283922871188272089,157,added an extra check while checking the padding
1,143019,1,233,568,055ecbc62878e86287d742c7246c21606cee8183,211824207069112513181516095447837228041,22,improve check for memory pseudo filename in sq...
2,270746,1,625,61,251fc70e9722f931eec23a34030d05ba5f747b0e,21401706257394042943815500829552774160,232,uncompress fix buffer underrun by corrupted in...
3,219494,1,588,604,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,135590882627853658533498335902319684573,66,cve 2007 1320 cirrus lgd 54xx bitblt heap over...
4,57922,1,588,604,b2eb849d4b1fdb6f35d5c46958c7f703cf64cfef,27696392987383562433164405181263025184,18,cve 2007 1320 cirrus lgd 54xx bitblt heap over...
...,...,...,...,...,...,...,...,...
320777,66231,0,404,509,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,191666183590885386921438642282124547733,8,src use unique ptr for writewrap this commit a...
320778,302076,0,404,509,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,257679158413882759024687732393060082473,11,src use unique ptr for writewrap this commit a...
320779,986,0,404,509,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,95849745532474044086293722840152017667,5,src use unique ptr for writewrap this commit a...
320780,295699,0,404,509,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,308185826333582152350706380559538897481,12,src use unique ptr for writewrap this commit a...
320781,289314,0,404,509,7f178663ebffc82c9f8a5a1b6bf2da0c263a30ed,13835898906479445212427382528307645781,221,src use unique ptr for writewrap this commit a...

In [54]:
#Final Check
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320782 entries, 0 to 320781
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   func       320782 non-null  int64
 1   target     320782 non-null  int64
 2   cwe        320782 non-null  int64
 3   project    320782 non-null  int64
 4   commit_id  320782 non-null  object
 5   hash       320782 non-null  object
 6   size       320782 non-null  int64
 7   message    320782 non-null  object
dtypes: int64(5), object(3)
memory usage: 19.6+ MB

func         0
target       0
cwe          0
project      0
commit_id    0
hash         0
size         0
message      0
dtype: int64

In [11]:
df_50k = df.sample(n=50000, random_state=42)

print(df_50k.shape)

df_50k.to_csv('/content/drive/MyDrive/Data Set/vulnerabilities_50k.csv', index=False)
display(df_50k)

(50000, 8)

,func,target,cwe,project,commit_id,hash,size,message
107954,"int tcp_disconnect(struct sock *sk, int flags)...",0,CWE-369,linux,499350a5a6e7512d9ed369ed63a4244b6536f4f8,314344658062900658806073024407233328050,72,tcp: initialize rcv_mss to TCP_MIN_MSS instead...
180818,void onEncodeComplete() override {},0,CWE-400,envoy,0e49a495826ea9e29134c1bd54fdeb31a034f40c,74867803835165829019802075929098677050,1,http/2: add stats and stream flush timeout (#1...
223963,vrend_renderer_fini(void)\n{\n vrend_state.f...,0,CWE-787,virglrenderer,95e581fd181b213c2ed7cdc63f2abc03eaaa77ec,11016301686342783913780871318765779847,19,vrend: Add test to resource OOB write and fix ...
262797,"void cgsleep_ms_r(cgtimer_t *ts_start, int ms)...",0,"CWE-20,CWE-703",sgminer,910c36089940e81fb85c65b8e63dcd2fac71470c,311680229030183643111393345484797160388,8,stratum: parse_notify(): Don't die on malforme...
226475,maketitle(void)\n{\n char_u\t*p;\n char_...,0,CWE-416,vim,9b4a80a66544f2782040b641498754bcb5b8d461,274646694900560327163673315852485978613,211,patch 8.2.4281: using freed memory with :lopen...
...,...,...,...,...,...,...,...,...
206664,static void restore_regs(const struct btf_func...,0,CWE-77,linux,e4d4d456436bfb2fe412ee2cd489f7658449b098,49161185225410789438905946844579780824,16,"bpf, x86: Validate computation of branch displ..."
48772,static bool ptrace_freeze_traced(struct task_s...,0,"CWE-284,CWE-264",linux,d049f74f2dbe71354d43d393ac3a188947811348,282442303980060067960214161840850482561,17,exec/ptrace: fix get_dumpable() incorrect test...
121461,"template<typename tp, typename tf, typenam...",0,CWE-125,CImg,10af1e8c1ad2a58a0a3342a856bae63e8f257abb,83309146422744962305267442290701841665,13,Fix other issues in 'CImg<T>::load_bmp()'.
164567,"int bnxt_re_create_cq(struct ib_cq *ibcq, cons...",0,"CWE-400,CWE-401",linux,4a9d46a9fe14401f21df69cea97c62396d5fb053,21737912048272334888700059363392238374,101,RDMA: Fix goto target to release the allocated...
172701,"hup_init_nhwindows(argc_p, argv)\nint *argc_p ...",0,"CWE-120,CWE-269",NetHack,f3def5c0b999478da2d0a8f0b6a7c370a2065f77,236046368324550116953703414853458062485,6,command line triggered buffer overruns\n\nPrev...